### ISSUE TITLE
subaccounts option causes the app to crash

### ISSUE THREAD

**Issue by olalekan-agbaje** [Flutterwave/Vue#24] opened 2022-11-29 17:28 UTC
When testing the subaccounts feature, is the key "`subaccounts`" or "`subaccount`".
While using subaccounts the application crashes with the error below. 

`v3.js:1 
Uncaught DOMException: Failed to execute 'postMessage' on 'Window': [object Array] could not be cloned.
    at q.readytorecieve (https://checkout.flutterwave.com/v3.js:1:29543)
    at t.PBFPubKey.F.<computed> (https://checkout.flutterwave.com/v3.js:1:31481)`

When using subaccount it works fine but the split transaction cannot be found in the flutterwave portal.

**Comment by ChijiokeOkorji** [comment] 2022-11-29 20:29
Hello Olalekan,

Thanks for contacting Flutterwave! 

My name is Chijioke, and I will be helping you today. To use subaccounts, you need to specify a `subaccounts` property in the payload and assign it to an array of objects. Here is an example payload:

`{
  tx_ref: (this as any).generateReference(),
  amount: "1000",
  currency:"NGN",
  redirect_url: "https://my-site.com",// your redirect destination for successful/cancelled transaction
  subaccounts: [
    {
      id: "RS_971FAAAD74DFEF48DB48194E1E34F323",// the subaccount id for splitting payments
    }
  ],
  customer: {
    name: "John Doe",
    email: "user@gmail.com",
    phone_number: "080******44",
  },
  customizations: {
    title: "Modal Title",
    description: "Customization Description",
    logo: "https://flutterwave.com/images/logo-colored.svg",
  },
  callback: (this as any).makePaymentCallback,
  onclose: (this as any).closeModalCallback,
}`

Please [click here to learn](https://developer.flutterwave.com/docs/collecting-payments/split-payments) more about subaccounts on Flutterwave. 

I hope this resolves your issue. ﻿If you have any further concerns, please reach out to us. We'll be happy to help.

**Comment by olalekan-agbaje** [comment] 2022-11-29 21:48
Please take a look at the code. Maybe you can spot anything out of place. I can test payments with the property as `subaccount` once I use `subaccounts` it crashes.



```
paymentData: {
    tx_ref: this.transaction_ref,
    amount: this.payment_info.amount,
    currency: 'NGN',
    payment_options: 'banktransfer,card,ussd,account',
    redirect_url: '',
    meta: {
        'service_name': this.payment_info.name + " fee payment",
        'service_description': this.payment_info.name + " payment description",
    },
    customer: {
        name: this.$attrs.auth.user.name,
        email: this.$attrs.auth.user.email,
        phone_number: '081845***044'
    },
    customizations: {
        title: 'Application Payment for ' + this.$attrs.auth.user.name,
        description: "",
        logo: ''
    },
    subaccounts: [
        {
            id: "RS_66D3BXXXXXXX3FDE035"
        },
        {
            id: "RS_DEC08XXXXXXX66D8B15"
        }
    ],
    callback: this.makePaymentCallback,
    onclose: this.closedPaymentModal
}
```

**Comment by ChijiokeOkorji** [comment] 2022-11-30 09:24
Please try modifying the payload with this:

paymentData = JSON.parse(JSON.stringify(paymentData));

The above code should prevent the cloning that you were previously
experiencing. Please let me know if this resolves your issue.

Also, for subsequent messages, please send them to either the GitHub page,
or Flutterwave's Developer Slack
<https://join.slack.com/t/flutterwavedevelopers/shared_invite/zt-1k8g97amf-DzBxovZSGgPMvWoBMkc8sw>
channel. This is so that it can be tracked, and more support can
be provided by teammates and other community members. Thank you!

**Comment by ChijiokeOkorji** [comment] 2022-11-30 10:03
Modification and explanation of the above code:

JSON.parse(JSON.stringify(this.paymentData));// I changed the parsed data
to this.paymentData

The code is used to make a copy of the payment data. This copy can then be
either passed to *this.asyncPayWithFlutterwave* (to fetch a payment link
asynchronously) or bound to the *<flutterwave-pay-button>* component.

**Comment by olalekan-agbaje** [comment] 2022-11-30 10:44
Thanks @ChijiokeOkorji This resolved the part of submitting the jobs using the `subaccounts` property. However, I still cannot see the split in my account.

**Comment by ChijiokeOkorji** [comment] 2022-11-30 13:36
Log into your Flutterwave Dashboard and click on Subaccounts. Next, click the Subaccount that you want to investigate to view more details. Let me know what you see there (if the transaction you performed is among the transactions listed).

**Comment by ChijiokeOkorji** [comment] 2022-11-30 14:52
Hello Olalekan. I'm sorry that you are experiencing this problem. I noticed that you passed two `id` objects in the subaccount array when generating a checkout link. Neither of them match the Account ID of the subaccount you shared above. To test that it is working properly, try passing only one `id` (the Account ID for this particular subaccount) when generating the checkout link.

**Comment by olalekan-agbaje** [comment] 2022-11-30 16:28
> Neither of them match the Account ID of the subaccount you shared above.

Thats very strange. I copied from the portal while in test environment. Everything I am doing is in test mode. I have double checked and they are the same ids. _**If you are referring to the above code snippet, the ids have been redacted with XXXX in between the id displayed above.**_

Secondly, while this (`SON.parse(JSON.stringify(this.paymentData));`) works to enable successful submission,

It creates a secondary issue where `callback: this.makePaymentCallback,` cannot be called after payment is done. This is the error thrown when using the code suggestion above.
`flutterwave-vue-v3.esm.js:280 Uncaught (in promise) TypeError: paymentParams.callback is not a function
    at Object.callback (flutterwave-vue-v3.esm.js:280:27)
    at v3.js:1:30788`

**Comment by toybz** [comment] 2022-12-03 08:34
Hello  @olalekan-agbaje  @ChijiokeOkorji 

I will be closing this now because we have resolved the issue on the Slack channel.
The issue is majorly not from the SDK but  from the split config and account resolve API.

Best regards.

**Closed by toybz** 2022-12-03 08:34 UTC
